### ISSUE TITLE
To do List

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#1]
### Todo and Ideas and bug list
Sorry i cannot do alot of c# work, but i can work on rest and hope a Coder will take over, or help on this ? Are you a coder willing to help feel free to contact me or PR any fixes.

In meantime ill try to give rest a facelift where i can in xml and textures =)
ill try contact original artist in credits for textures, see if they wanna redo their work before i just remove it from the mod.
That way it feels like original thing =)

## bugs:
- [x] Update assemblies / fix assembler/cooker placing error (Possible assemblies?)
- [ ] I remeber that in the previous version pawn would loop hauling stuff from the cargobox (take from cargobox A to drop in cargobox A).

## C# todo
- [ ] ProjectRimFactory.Storage.Building_StorageUnitIOPort make it show by color/texture if its set to in/output by comp/expansion?
- [ ] Cultivators Shall have Output cell like old one have.
like ProjectRimFactory.CultivatorTools.Building_Cultivator instread of ..DroneCultivator

## Ideas
- [x] Make a way to pull from Hydroponics to growzone, field or roller. (new puller?)
- [ ] Patch for dubs hygiene for sprinkler to use
- [ ] New textures for animal station
- [x] Normal Cultivator need Help icon
- [ ] Copy Recipe database or pull bills from assemblers (for backup/duplicate)
- [x] SS batteries + research into this mod
- [x] Storage back in
- [x] Balance deep drill research/cost to compared to vanilla
- [x] Update storage textures
- [x] Change size on Research table
- [x] Remove paper clip research from research
- [x] Industrial Roller patch

Ideas not tasked yet, thoughts?
- Make research Industrial rollers stuff into prf ones?
- Removed stuffed from Animal station and merge them?

Feel free to suggest, ideas and post any bugs so i can put them to work.
can be posted here or on steam workshop page.

more help testing and ideas, means more time for me to update mod instead of doing both.
