### ISSUE TITLE
Assemblers output (Merged)

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#168]
_Okay this issue collects:_
Issue #83 cannot output into a wall
Issue #118 Waiting state dont count towards x

**Might also look at**
#123 mute masterwork issue

### Todo
So to sum up this is what we should do:

- [x] Assemblers should not be able to ouput into a wall.
- [x] It should properly have the Blocked output label too.
- [x] Blocked output are fine, and it will go into waiting to place state
- [x] IF Waiting state are being too big, 100 items waiting to be placed or something, it will stop produce anymore items.
- [x] It should also Change label to BLOCKED OUTPUT if so.
- [ ] We could also add smoke effect or something else if blocked to indicate a problem.
- [x] LWM talked about we could make it a storage building to count its "stored" content towards X

**Side note**
A fun addition could be to add a event if a blocked output being blocked for too long or if ignore limit part and being overfilled to greatly like 50 items, smoke, 100 items glow,
200 items BOOOM.

**Comment by zymex22** [comment]
might be done same with #228
