### ISSUE TITLE
Future for DSU

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#342]
### Digital Storage Unit Update
Okay now that 2.5.0 is out of the way and we are moving along with buug fixing for all the new stuff i might as well put in my future todo for DSU as we getting a lot of suggestions and such for it.

**Open Issues / request regards DSU**
- [ ] #58 figuure what to do with NoMessyRespawn
- [ ] #178 Add Category search (only main ones weapon, buildings, food, materials NO SUB)
- [ ] #300 need a button to turn off Fuuzzy Search

### Other things we should consider to do
- [ ] Look into reported bugs on Jobs of opputunity / PUAH (loop error)
- [ ] Do sort/reorginize buttons still have a purpose/work ?
- [ ] On Spdskatr's original todo he had a next tier storage from DSU

### Suggestions i think may be a good idea:
- [ ] Dimensional I/O ports (should be a seprate DEF) (across map or for SoS)
- [ ] Assemblers can import/export directly from a DSU (maybe a t4 assembler?)
- [ ] Link DSU together so they use one item list.
This could be done with some cables we can call Bus cables.
- [ ] Make a Vacuum I/O port (smart hopper+I/O in one) tier 2 I/O port probably.

### Additional info
Nobo made a system he called AutomationNet it was however Scrapped because ppl didnt understand how to use it and set it up, and he wasnt able to find a good way to explaing it. so he just commented it out from his mod.
Basicly its a system that lets you connect Stockpiles together with cables, so it can fill each other when needed.
it sounds like something we maybe could use for our DSU if we wanna link them together.

It can be found here, just commented out, but still in the mod, and working if uncomment, Daemon tested it if more info needed.
https://github.com/nullre/rw_mods/blob/master/NR_AutoMachineTool/Defs/ThingDefs/NR_AutoMachineTool/NR_AutoMachineTool_AutomationNet.xml

### New DSU system (Main controller + Network)
As stated before i would love to see a Storage system that can be connected via cables (buus cables/automationNet etc...)
So you set up one main controller and from this you can connect your items into it with our special cables, that would be DSU, Assemblers, I/O and maybe more ?.
This would allow you to search entire "network" when looking for a item in storage.
and it would let your assemblers in and output directly into a dsu without need for I/O, belts or pawns to fill them.

I guess its kinda like applied energistics for those who has played minecraft :P
This controller could later also maybe be used to do other things like control connected machines and such, i guess kinda like how it is in RimAtomix/RimaFeller mod where there is a "Main Machine"
This may also help us guide user better because we could use that one to share info on stuff

**Comment by Sn1p3rr3c0n** [comment]
> Do sort/reorginize buttons still have a purpose/work ?

The "PRFReorganize_Message" Gizmo will call the `RefreshStorage()` Method.
This method is automatically called when an item is added or removed from the DSU.
It will update an internal list of Items.

I'm not sure if the automatic calls cover all cases.
My guess is that it is there to manually trigger should the automatic option fail.

_But that is not really user friendly. We should check that all cases are covered and then remove it i think._
- [ ] ^^

**Comment by grapemix** [comment]
I am always wondering why does my Assemblers and advanced Assemblers not working w/ my advance IO port + my DSU. I am looking forward for this feature. Thanks guys. Great work.
