### ISSUE TITLE
(Request) Enhanced Logic functionality

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#433]
> originally requested by `Curt` on Discord

The current Logic capability of things like pullers is limited to the items that they are allowed to pull + the optional limit on the item Count.

However sometimes it would be beneficial to trigger certain things based upon different & more complex logical Conditions.
non-exhaustive sample list:
- Pull X & Y until Z has B amount
- Pull X if X has more then B amount and Y has less the C amount
-  ...

---

My current vision of how something like this could look like:

New Building: `Logic Controller`
- 2x2 or 3x3
- 1 per map
- _Dynamic name based on map name_

Controller has an ITab
- user can configure `Logic Signals` (think if conditions with True/False value)
- `Logic Signals` can depend on other `Logic Signals`
- `Logic Signals` can be named
- _only_ access tho things on its own map but can reference `Logic Signals` of different maps

---

open for feedback & Ideas of how such i system could or should look like.

**Comment by Sn1p3rr3c0n** [comment]
**Use cases to consider**

- Action on: Have at least 20x A OR 50x C _(in some slotgroup)_ **(covered)** 
--> make Chemfuel from Rice if we have more the 1k in storage AND ( we have more then 20 Lavish Meals OR 50 Simple Meals)

- Action-1 if 20x A ; Action-2 if 50x C
--> Have a single Puller Pull Meat and Veggies if we need Lavish Meals BUT if we need Simple Meals only Pull Veggies 

- _(Unsure)_ Execute Action only every X seconds / Ticks
--> The fulfillment of the conditions might not be immediately satisfied, this could cause that too many Items get moved

- Move X Amount of Items if a condition is meat
--> ? How would a re-trigger be handled ?
--> this could be the better solution to the case above / Combine with the case above to solve the re-trigger
--> If my Pocket Dimension has less then 10 meals give them 5 more

- Reference `Storage Locations` from the device Reacting on the Action
--> Input / Output Cell of a puller
--> own storage of a belt (#441)

---

Please feel free to post Suggestions if I have missed a Use Case.

**Comment by Sn1p3rr3c0n** [comment]
### Current Status

The Logic Controller has 3 Tabs:
- Values
Used to Create and Edit Values References
- Leaf Logic
Used to Compare Values 
- Algebra
Used to Create Signals
---
**Values**
Tab Overview:
![image](https://user-images.githubusercontent.com/68663281/117958691-8f06ab80-b31b-11eb-8c6a-8acc66205b76.png)


There are 3 Sub Types for Values
1. Fixed Values
Just a fixed Value. You can enter a name and a Value 
![image](https://user-images.githubusercontent.com/68663281/117958785-a8a7f300-b31b-11eb-8ef3-56570d80efb0.png)
2. Item References
Configure a Thing Filter & Select a Zone.
You can also configure a name.
For the Zone You can Select any Zone or Storage Building. 
There are 3 Additional options for the Zone:
- `Entire Map` Self explanatory
- `Dynamic - 1` Dynamic Storage Zone provided by the Building using the Signal
- `Dynamic - 2`Dynamic Storage Zone provided by the Building using the Signal
There are 2 Dynamic Zone so that 1 can be the Input and the other the Output
![image](https://user-images.githubusercontent.com/68663281/117960158-0426b080-b31d-11eb-89b9-61e58e2bbad9.png)
3. Signals
Any already configured Signal _(Signals should be available cross map)_
![image](https://user-images.githubusercontent.com/68663281/117960252-1acd0780-b31d-11eb-8e28-5b238fc94ab7.png)
---
**Leaf Logic**
![image](https://user-images.githubusercontent.com/68663281/117960656-7e573500-b31d-11eb-8b10-a336c2d99580.png)
Compare two Value References.
You can enter a Name, Select the Signals and choose the Compare Operator

---
**Algebra**
![image](https://user-images.githubusercontent.com/68663281/117960998-e4dc5300-b31d-11eb-945a-d90d31ff87ac.png)
[Boolean algebra](https://en.wikipedia.org/wiki/Boolean_algebra) Editor. 
You can Edit the Name.
The Rectangle provides an indexation whether or not the Edited Expression is valid. (Green = Valid ; Red = Invalid)
With the Reload Button the user can recover the last saved Version of the Expression
With the Save Button the user can save the Expression assuming its Valid.


---
**TODO:**

- [ ] Names used here are need to be updated but be easier to understand
- [ ] Use Language Files
- [ ] Add Support for `Not` to the Expression Based Algebra Editor
- [ ] Add Support for `(` & `)` to the Expression Based Algebra Editor
- [ ] Continue the work on the Drag & Symbol Based Algebra Editor _(kinda complicated)_ (Drag & Hotboxes are implemented)
- [ ] Enhance the List boxes for the different `Values` , `Leaf Logic Elements` and `Signals`  
- [ ] Finalize ITab Design
- [ ] Implement & add Logic on the Receiver Side (`Puller` , `Belt`? , ...)
- [ ] Allow Signals to be Referenced Cross Map
- [ ] XML Stuff
- [ ] Graphic for the Logic Controller
- [ ] ...
