### ISSUE TITLE
Known bug list

### ISSUE THREAD

**Issue by zymex22** [zymex22/Project-RimFactory-Revived#52]
I dedicate this weekend to track down bugs and issues and try fix as many as possible, so PLEASE post any bug, issue, typo or info on existing ones, so i can adress them and try fix them.

### Bug list prf
- [x] Cooker room poison #48 (Done by MadaraUchiha)
- [x] Furnace/spacer cooker fps drop?
- [ ] Fuel use on Furnace (comp need added to thingclass)
- [ ] Change T1 miner to Fuel
- [x] Texture Graphic options
- [x] Building layer (some seem strange)
- [x] Problem when placing assemblers to connect to db #54 

### Buglist mod compat.
- [ ]  Pullers sometimes fail to push items into deep storage (LWM)
- [ ] Apothecary imcompat with cultivators #27 
- [x] Bug with Tiny Tweak and Skill decay + drones

Please feel free to add any info or new bugs here so we can try to fix them together! =)

**Comment by zymex22** [comment]
BUG Deep Drill?

> Hi i added this Mod to my existing game but removed it again later. Now my Scanner and Deep Drills dont show the discovered minerals on the map anymore. Reloading doesn't help and even newly discovered minerals are not shown. Any suggestions what to do?

> The Deep drill fix kinda worked, but caused the issue that Nukor252 posted earlier. Deep drill doesn't show the green/yellow/red overlay to let you know there's ore in that area, however your deep drill mines whatever ore the scanner found, so moving the drill to right spot can be a guessing game.

=========
Furnace FPS bug

> @zymex - after 2 days of troubleshooting my 250+ modlist I figured out what was causing the spacer cooker to slow down my game. it appears to be the number of individual light sources on the map, not the cooker itself.
> I had a mod that made conduits emit light. was great base lighting but using it instead of normal conduit created thousands of light sources. once I removed that mod, adding the spacer cooker did not impact the ticks per second.


> Now I'm confused, I tried making all three of the furnaces and im not seeing a performance drop again. Though something did pop up on the debug log
> ```
> Exception ticking PRF_FurnaceI272212: System.NullReferenceException: Object reference not set to an instance of an object
> at Verse.GenGrid.Walkable (Verse.IntVec3 c, Verse.Map map) [0x00000] in <4489f1367c1c4d76b2ae1272c8ed691d>:0 
> at ProjectRimFactory.SAL3.Things.Assemblers.Building_ProgrammableAssembler.Tick () [0x00042] in <ff37a1d882524a2f858ced512662e40f>:0 
> at Verse.TickList.Tick () [0x0015c] in <4489f1367c1c4d76b2ae1272c8ed691d>:0 
> Verse.Log:Error(String, Boolean)
> Verse.TickList:Tick()
> Verse.TickManager:DoSingleTick()
> Verse.TickManager:TickManagerUpdate()
> Verse.Game:UpdatePlay()
> Verse.Root_Play:Update()
> ```
> I still believe the original performance drop was caused by the industrial furnace as the drop started when the industrial furnace was placed and stopped immediately after it was destroyed. Also, I don't know if this was intentional or not but it doesn't seem like the electric furnace is capable of smelting rock chunks into stone bricks.

**Comment by MadaraUchiha** [comment]
I've submitted a PR to fix #48. Here it is: #51. Let me know if you want me to do anything else.

**Comment by zymex22** [comment]
i'll test it later today and release if working =)

Feel free to post any other bugs or help solve out those already on list =) could be cool to get some of those small bugs fixed before moving on to new things =)

**Comment by zymex22** [comment]
**Building layer (some seem strange)**
Ricki 10. may kl. 9:59 

> Hey first of all: This mod is awesome! Thank you. A few minor things:
> 
> 1) Rimfactory textures seem to be one of the few textures that are in the foreground instead of the background. This can often look weird (floaty) and make for strange interactions. Especially for digital storage this thends to look very floaty when pawns pass the corners.
> 
> 3) (Rimfactory) Pushers sometimes fail to push items into (LMW) deep storage (thanks for supporing deep storage btw) and just toss them next to the container. I'll get you a minmial savegame/and or steps to reproduce when I have time again to play next week.

**Comment by Zymex** [comment]
Not sure why I am tagged in this. Please make sure you reference the person you are looking for and not someone else.

Thanks

**Comment by Silfalion** [comment]
Significant lags when using too many digital storage unit that are filled.
