### ISSUE TITLE
(Request) Setup GitHub Action to build and publish a release

### ISSUE THREAD

**Issue by Sn1p3rr3c0n** [zymex22/Project-RimFactory-Revived#544]
I think it would be cool if we could setup a Action to automatically build the PRF dll and upload it as a new release to GitHub.

Could maybe be trigged based upon a new tag on the master branch.

**Comment by zymex22** [comment]
i have no idea how such thing would work, but it sounds awesome as it would mean i dont need to dl and build and upload again to github =) ofc i will need to steam but still better ;D

**Comment by Sn1p3rr3c0n** [comment]
Still trying to fully understand it but it seems promising.

Automatic release
https://github.com/Sn1p3rr3c0n/Project-RimFactory-Revived/releases/tag/2.3.0
```yml
name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Source.sln
    - name: Build
      run: dotnet build Source/Source.sln --no-restore
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "Assemblies/ProjectRimFactory.dll"
        #bodyFile: "body.md"
        body: "#body"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: 2.3.0
```

**Todo**
- [ ] Upload repo with dll in the attachments
- [ ] provide a proper Body
- [ ] Check for release note Gen stuff

**Comment by Sn1p3rr3c0n** [comment]
a bit of progress again

https://github.com/Sn1p3rr3c0n/Project-RimFactory-Revived/releases/tag/v2.3.1
the automatically generated change list looks airtight although I would prefer if I would display the issue title or we could otherwise provide a proper description.

```yml
name: .NET

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Source.sln
    - name: Build
      run: dotnet build Source/Source.sln --no-restore
    - name: Check for modified files
      id: git-check
      run: echo ::set-output name=modified::$(if [ -n "$(git status --porcelain)" ]; then echo "true"; else echo "false"; fi)
    - name: Upload Build
      if: steps.git-check.outputs.modified == 'true'
      run: |
          git config --global user.name 'Sn1p3rr3c0n'
          git config --global user.email 'Sn1p3rr3c0n@users.noreply.github.com'
          git commit -am "Updated dll"
          git push
    - uses: ncipollo/release-action@v1
      with:
        #bodyFile: "body.md"
        body: "some manual content"
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: v2.3.1
```
- [ ] provide a proper Body (or maybe just leave it empty for now)
- [ ] Check for possible triggers
- [ ] Automatically generate a Tag for the Release
- [ ] maybe update the manifest file as well with the new version

**Comment by Sn1p3rr3c0n** [comment]
it seems like the [dll generated by the build job](https://github.com/zymex22/Project-RimFactory-Revived/commit/ce222ee8f0b810f442e751dacb23827370f1ae4c) is ~18KB larger then when i build it on my PC.
i wonder what could cause this.

**Comment by Sn1p3rr3c0n** [comment]
Closing issue as the current Implementation works reasonably well
Update the Version → Run the Action → minimal Edits to the Draft Release → Done
