### ISSUE TITLE
 (Bug report?)

### ISSUE THREAD

**Issue by brucethemoose** [zymex22/Project-RimFactory-Revived#639]
I'm not following the usual format because I'm not sure this is an issue with Rimfactory.

When running Dub's Performance Analyzer with Rimfactory (and hugslib), if the "transpiler" tab is open, it errors out with this message: 

'[Analyzer] Failed to patch transpiler, failed with the message Method System.Void Verse.Map::FinalizeLoading() cannot be patched. Reason: Invalid IL code in (wrapper dynamic-method) Verse.Map:Verse.Map.FinalizeLoading_Patch0 (Verse.Map): IL_004b: stloc.2 `

https://gist.github.com/HugsLibRecordKeeper/9b0a840def4d2aa5402cea765ba1594e#file-output_log-txt-L134

Looking back through the log, this is the only bit that patches that method: `Map.FinalizeLoading: TRANS: SimpleFixes.Patches.Map_FinalizeLoading.Transpiler`

In then proceeds to bug analyzer out (which @Dubwise56 may be interested in), but my bigger worry is that this is simply a warning from Analyzer that something else in PRF is busted? What does this "SimpleFixes" transpiler do, and should I be worried that the invalid code warning from DPA?

**Comment by Sn1p3rr3c0n** [comment]
That Class `SimpleFixes` dose not directly belong to our Code but it belongs to a library that we use: `0NoMessySpawns`.

This probably means that that lib might have broken in 1.4 in some way.

**Todo:**
- [ ] Check why that error only shows up when opening the analyzer
- [ ] Will `0NoMessySpawns` need a fix?
- [ ] consider the above for #58
- [ ] (Re)Check what exactly `0NoMessySpawns` dose _(I am personally not fully aware)_

**Comment by brucethemoose** [comment]
It appears that [DoctorVanGogh](https://github.com/DoctorVanGogh) (the maintainer for that library hasn't been active in RW since 2020. Not sure if they are still around.

**Comment by Sn1p3rr3c0n** [comment]
@brucethemoose
We (@InsanityPrelude & myself) have been discussing it it on Discord.
We are currently unable to find a reason on why it would be needed it, so we will probably just remove it.
